course_pool/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('courses.urls')),
]

courses/urls.py
from django.urls import path
from django.urls import include
from .views import CustomLoginView, RegisterPage
from django.contrib.auth.views import LogoutView
from django.contrib.auth import views as auth_views
from django.urls import reverse_lazy

from . import views

app_name = 'courses'

urlpatterns = [
    path('', views.index, name='index'),
    path('search', views.search_course, name='search_course'),
    path('category/<str:key>', views.category, name='category'),
    path('toggle_favorite', views.toggle_favorite, name='toggle_favorite'),
    path('favorite', views.show_favorite, name='favorite'),
    path('suggest_course', views.suggest_course, name='suggest_course'),
    path('login/', CustomLoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(next_page='courses:login'), name='logout'),
    path('register/', RegisterPage.as_view(), name='register'),
    path('reset_password/',
         auth_views.PasswordResetView.as_view(
             template_name="courses/password_reset.html",
             email_template_name='courses/password_reset_email.html',
             success_url=reverse_lazy('courses:password_reset_done')),
         name="password_reset"),

    path('reset_password_sent/',
         auth_views.PasswordResetDoneView.as_view(
             template_name="courses/password_reset_sent.html"),
         name="password_reset_done"),

    path('reset/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(
             template_name="courses/password_reset_form.html",
             success_url=reverse_lazy('courses:password_reset_complete')),
         name="password_reset_confirm"),

    path('reset_password_complete/',
         auth_views.PasswordResetCompleteView.as_view(
             template_name="courses/password_reset_done.html"),
         name="password_reset_complete"),

]

courses/models.py
from django.db import models
from django.contrib.auth.models import User


class Course(models.Model):
    course_name = models.CharField(max_length=250)
    author = models.CharField(max_length=250)
    url = models.URLField()
    thumbnail_url = models.URLField()
    description = models.TextField()
    tags = models.CharField(max_length=250)

    def __str__(self):
        return self.course_name

    def get_tags(self):
        tags = self.tags.split(',')
        return tags


class Your_Course(models.Model):
    user = models.ForeignKey(
        User, on_delete=models.CASCADE, null=True, blank=True)
    course_id = models.IntegerField()

    def __str__(self):
        return str(self.user) + ' - ' + str(self.course_id)


class Suggest_Course(models.Model):
    name = models.CharField(max_length=150)
    email = models.EmailField(max_length=150)
    course_name = models.CharField(max_length=250)
    course_url = models.URLField()
    description = models.TextField()

    def __str__(self):
        return self.course_name

courses/views.py
from .models import Course, Your_Course
from courses.util import get_courses
from courses.form import UserCreationForm, SuggestCourseForm
from django.contrib.auth.models import User

from django.contrib.auth.views import LoginView, PasswordResetView
from django.contrib.auth.forms import PasswordResetForm
from django.views.generic.edit import FormView
from django.db.models import Q
from django.http import JsonResponse
from django.urls import reverse_lazy
from django.contrib.auth import login
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
import json


def index(request):
    all_courses = get_courses(request, is_search=False)

    context = {'courses': all_courses}
    return render(request, 'courses/courses.html', context)


def search_course(request):
    keyword = request.GET.get('key')

    if not keyword:
        all_courses = get_courses(request, is_search=False)
        context = {'courses': all_courses}
        return render(request, 'courses/courses.html', context)

    keyword = " ".join(keyword.split())
    print(keyword)
    courses = get_courses(request, is_search=True, keyword=keyword)

    context = {'courses': courses, 'keyword': keyword}

    return render(request, 'courses/search.html', context)


def category(request, key):
    courses = get_courses(request, is_search=True, keyword=key)
    context = {'courses': courses, 'tag': key}

    return render(request, 'courses/courses.html', context)


def toggle_favorite(request):
    data_from_post = json.load(request)['course_id']
    course_id = data_from_post.split('-')[-1]
    if Your_Course.objects.filter(user=request.user).filter(course_id=course_id):
        Your_Course.objects.filter(user=request.user).filter(
            course_id=course_id).delete()
    else:
        q = Your_Course(user=request.user, course_id=course_id)
        q.save()
    return JsonResponse({})


class CustomLoginView(LoginView):
    template_name = 'courses/login.html'
    fields = '__all__'
    redirect_authenticated_user = True

    def get_success_url(self):
        return reverse_lazy('courses:index')


class RegisterPage(FormView):
    template_name = 'courses/register.html'
    form_class = UserCreationForm
    redirect_authenticated_user = True
    success_url = reverse_lazy('courses:index')

    def form_valid(self, form):
        user = form.save()
        if user is not None:
            login(self.request, user)
        return super(RegisterPage, self).form_valid(form)

    def get(self, *args, **kwargs):
        if self.request.user.is_authenticated:
            return redirect('courses:index')
        return super(RegisterPage, self).get(*args, **kwargs)


@ login_required(login_url='courses:login')
def show_favorite(request):
    favorite_courses = {}
    favorite_id = [
        c.course_id for c in Your_Course.objects.filter(user=request.user)]
    for c in Course.objects.filter(id__in=favorite_id):
        favorite_courses[c] = True
    context = {'favorite_courses': favorite_courses}
    return render(request, 'courses/favorite.html', context)


def suggest_course(request):
    # if this is a POST request we need to process the form data
    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        form = SuggestCourseForm(request.POST)
        if form.is_valid():
            form.save()
            context = {'form': SuggestCourseForm(), 'success': 1}
            return render(request, 'courses/suggest_course.html', context)
    else:
        form = SuggestCourseForm()

    return render(request, 'courses/suggest_course.html', {'form': form})

courses/templates/courses/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://kit.fontawesome.com/da72a545a2.js" crossorigin="anonymous"></script>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'courses/css/bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'courses/css/style.css' %}">
    <link rel="shortcut icon" type="image/png" href="{% static 'courses/img/favicon.ico' %}" />

    <title>{% block title %}Course Pool{% endblock %}</title>
</head>

<body>
    <!-- Navbar container -->
    <nav id="navbar">

        <div class="navbar navbar-expand-md navbar-dark bg-dark">
            <a class="navbar-brand flex-shrink-0 order-md-1 ms-2 me-1 d-flex justify-content-center align-items-center"
                href="{% url 'courses:index' %}"><img class="logo" src="{% static 'courses/img/logo.png' %}" alt=""></a>

            <button class="navbar-toggler ms-auto order-md-3" type="button" data-bs-toggle="collapse"
                data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false"
                aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <!-- Account -->
            <div class="order-md-4 mx-2 dropdown fs-5">
                <a href="" role="button" id="dropdownMenuLink" data-bs-toggle="dropdown" aria-expanded="false"><i
                        class="fas fa-user-circle fa-2x text-white-50"></i></a>
                <ul class="dropdown-menu dropdown-menu-dark dropdown-menu-end" aria-labelledby="dropdownMenuLink">
                    {% if request.user.is_authenticated %}
                    <li>
                        <p class="dropdown-item text-name-login my-0 pb-1" href="#">{{request.user.first_name}}
                            {{request.user.last_name}}</p>
                    </li>
                    <li><a class="dropdown-item" href="{% url 'courses:logout' %}">Logout</a></li>
                    {% else %}
                    <li><a class="dropdown-item" href="{% url 'courses:login' %}">Login</a></li>
                    {% endif %}

                </ul>
            </div>
            <!-- Main Menu -->
            <div class="collapse navbar-collapse order-md-2 ms-2" id="navbarNav">
                <ul class="navbar-nav">
                    <li class=" nav-item px-sm-2">
                        <a class=" nav-link navbar-text" id="home" href="{% url 'courses:index' %}">Home</a>
                    </li>
                    <li class="nav-item px-sm-2">
                        <a class="nav-link navbar-text " id='favorite' href="{% url 'courses:favorite' %}">Favorite</a>
                    </li>

                    <li class="nav-item px-sm-2">
                        <a class="nav-link navbar-text " id="suggest" href="{% url 'courses:suggest_course' %}">Suggest
                            a
                            Course</a>
                    </li>
                </ul>

            </div>
        </div>
    </nav>

    <main>

        {% block content %}

        {% endblock %}
    </main>

    <footer>
        <div class="text-center text-light py-2">
            <p>Made with <span class="fas fa-heart px-1"></span> & <span class="fa fa-coffee px-1"></span>
                by <span class="text-name-footter">Hung Tran</span></p>
            <p class="mb-2">Want to see more projects like this? </p>
            <a class="text-light" href="https://github.com/QuocHung52" target="_blank"><i
                    class="fab fa-github fa-2x"></i></a>

        </div>
        <div class="seperate-line"></div>
        <div class="text-light text-center pt-2">
            <p> &copy; 2021 All Right Reserved</p>
        </div>
    </footer>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4"
        crossorigin="anonymous"></script>

    <script src=" {% static 'courses/js/script.js' %}">
    </script>
    <!-- <script src="{% static 'courses/js/bootstrap.min.js' %}"></script> -->




</body>


</html>

courses/templates/courses/course_template.html
<!-- Template course view -->
{% load social_share %}

<div class="d-flex justify-content-center align-items-center pb-2">
    <div class="container grid-view">
        {% for course, is_favorite in courses.items %}
        <div class="course-card position-relative " id="course_{{course.pk}}">
            <a class="img-course" href="{{course.url}}" target="_blank">
                <img src="{{course.thumbnail_url}}" alt="Course Image">
            </a>
            <div class="tag-list">
                <ul class="d-flex flex-wrap mt-1 mx-auto">
                    {% for tag in course.get_tags%}
                    <li>
                        <a href="{% url 'courses:category' tag%}">{{tag}}</a>
                    </li>
                    {% endfor %}
                </ul>
            </div>
            <div class="course-name">{{course.course_name}}</div>
            <div class="author">by <span class="author-name">{{course.author}}</span></div>
            <div class="description">
                <p>{{course.description}}</p>
            </div>
            <div class="d-flex justify-content-center align-items-center my-3">
                <div class='position-absolute bottom-0 my-2 d-flex align-items-center  w-100'>
                    <a class="ms-3" href="{{course.url}}" target="_blank">
                        <button type="button" class="btn btn-info">Learn More</button>
                    </a>
                    <div class="ms-3">
                        <!-- Button trigger modal -->
                        <button type=" button" class="btn btn-info" data-bs-toggle="modal"
                            data-bs-target="#share-course-{{course.id}}">Share <i class="fas fa-share-alt"></i></button>

                        <!-- Popup Share Modal -->
                        <div class="modal fade" id="share-course-{{course.id}}" tabindex="-1"
                            aria-labelledby="share-course-modal-label" aria-hidden="true">
                            <div class="modal-dialog modal-dialog-centered ">
                                <div class="modal-content bg-dark">
                                    <div class="modal-header">
                                        <h5 class="modal-title text-light" id="share-course-modal-label">Share this
                                            course</h5>
                                    </div>
                                    <div class="modal-body ">
                                        <div class="d-flex justify-content-center align-items-center">
                                            {% post_to_facebook course.url " " "facebook-custom mx-3 " %}
                                            {% post_to_twitter " " course.url " " "twitter-custom mx-3" %}
                                            {% post_to_reddit " " course.url " " "reddit-custom mx-3 " %}
                                            {% post_to_whatsapp course.url " " "whatsapp-custom mx-2 " %}
                                        </div>
                                    </div>
                                    <div class="modal-footer">
                                        <button type="button" class="btn btn-secondary"
                                            data-bs-dismiss="modal">Close</button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    {% if request.user.is_authenticated %}
                    {% if is_favorite %}
                    <div class="text-warning ms-auto me-3 toggle-favorite" id="course-{{course.id}}"><i
                            class="fas fa-star fa-2x"></i>
                    </div>
                    {% else %}
                    <div class="text-warning ms-auto me-3 toggle-favorite" id="course-{{course.id}}"><i
                            class="far fa-star fa-2x"></i>
                    </div>
                    {% endif %}
                    {% endif %}
                </div>
            </div>
        </div>
        {% endfor %}
    </div>

</div>

courses/templates/courses/courses.html
{% extends 'courses/base.html' %}
{% load static %}
{% load social_share %}

{% block content %}
<!-- Slogan -->
<div class="slogan text-light bg-dark">
    <div class="slogan-container">
        <h1>No Need to Pay</h1>
        <p>We have some great free courses for you!</p>
    </div>
</div>

<!-- Search bar -->
<div class=" my-2 mb-3 search-bar ">
    <form class="input-group" action="{% url 'courses:search_course' %}">
        <input class="form-control rounded-start" type="text" name="key" placeholder="Python, JavaScript, Swift...">
        <button class="btn-outline-light bg-info text-dark rounded-end" type="submit"><i
                class="fas fa-search px-2"></i></button>
    </form>
</div>

<!-- Main content -->
{% if tag %}

<div class="d-flex align-items-center justify-content-center pt-4 pb-2">
    <h3 class="text-light ">Courses with tag: <span class="text-warning"> {{tag}} </span></h3>
</div>

{% else %}
<h2 class="text-light text-center py-4">Top picks from us!</h2>

{% endif %}

{% include "courses/course_template.html" with courses=courses %}



{% endblock %}

courses/templates/courses/favorite.html
{% extends 'courses/base.html' %}
{% load static %}

{% block content %}

<!-- Slogan -->
<div class="slogan text-light">
    <div class="slogan-container">
        <h1 class="mb-3">Your Favorites</h1>
        {% if not favorite_courses %}
        <p class="fs-5">Seems like you don't have any favorite Course</p>
        {% endif %}
        <p class="fs-6">Click the <i class="fas fa-star"></i> icon below courses to set them as your favorites </p>
    </div>
</div>
{% if request.user.is_authenticated %}

<!-- Main content -->
{% include 'courses/course_template.html' with courses=favorite_courses %}


{% endif%}

{% endblock %}

courses/templates/courses/login.html
{% extends 'courses/base.html' %}
{% load static %}

{% block content %}



<div class="container text-light py-2">
    <div class="row d-flex justify-content-center">
        <div class="col-md-6 col-lg-4 col d-flex justify-content-center ">
            <div class="login-wrap">
                <div class=" d-flex justify-content-center mb-0">
                    <img src="{% static 'courses/img/login.png' %}" alt="Login Logo" id="login-logo">
                </div>
                <h2 class="text-center login-title pt-3 pb-md-1">Welcome
                </h2>
                <!-- TODO: Sign in with google methods -->
                <!-- <p class="text-center">Sign in with google</p> -->


                <form class="form login-form" method="POST">{% csrf_token %}
                    <div class="form-group mb-3">
                        <div class="icon d-flex justify-content-center align-items-center"><span
                                class="fa fa-envelope"></span></div>

                        <input class=" form-control" autocapitalize="none" id="Email address" type=" text"
                            name="username" placeholder="Username" required>
                    </div>
                    <div class="form-group mb-4">
                        <div class="icon d-flex justify-content-center align-items-center">
                            <span class="fa fa-lock"></span>
                        </div>
                        <input class=" form-control" id="id_password" type="password" name="password"
                            placeholder="Password" minlength="8" required>
                    </div>
                    {% if form.errors %}
                    <div class="form-group">
                        <div class="w-100 d-flex justify-content-center">
                            <p class="text-danger">Your username and password didn't match. Please try again.</p>
                        </div>
                    </div>
                    {% endif %}
                    <div class="form-group">
                        <div class="w-100 d-flex justify-content-end mb-3 ">
                            <a href="{% url 'courses:password_reset' %}">Forgot Password?</a>
                        </div>
                    </div>
                    <div class="form-group">
                        <button type="submit" class="btn form-control btn-primary rounded submit px-3">Get
                            Started</button>
                    </div>

                </form>
                <div class="w-100 text-center mt-4 text">
                    <p class="mb-0">Don't have an account?</p>
                    <div>
                        <a href="{% url 'courses:register' %}"><button class="btn btn-secondary">Sign Up</button></a>

                    </div>
                </div>


            </div>

        </div>
    </div>
</div>


{% endblock content %}

courses/templates/courses/password_reset.html
{% extends 'courses/base.html' %}
{% block content %}

<div class="row justify-content-center py-3">
    <div class="login-wrap py-5">
        <h2 class="text-light text-center fw-bold fs-2">Forgot your password?</h2>
        <p class="text-center">Enter your email address below, and we'll email instructions for setting a new one.</p>

        <form method="POST">
            {% csrf_token %}

            <input class="mb-3 form-control" type="email" name="email" id="id_email" required
                placeholder="Email Address" autocomplete="email">

            <div class="w-100 d-flex justify-content-center">
                <input class="btn btn-primary" type="submit" value="Send me instructions!">
            </div>
        </form>
    </div>
</div>

{% endblock %}

courses/templates/courses/password_reset_done.html
{% extends 'courses/base.html' %}
{% block content %}



<div class="row justify-content-center py-3 mx-3 py-md-5">
    <div class="login-wrap py-3">

        <h3 class="text-light fw-bold fs-1">Password reset complete</h3>

        <p>Your password has been set. You may go ahead and log in now.</p>

        <div class="row">
            <a class="text-light text-center" href="{% url 'courses:login' %}">
                <button type="submit" class="btn btn-primary px-3 text-light">Log
                    in</button>
            </a>
        </div>



    </div>

</div>


{% endblock %}

courses/templates/courses/password_reset_email copy.html
{% load i18n %}{% autoescape off %}
{% blocktranslate %}You're receiving this email because you requested a password reset for your user account at {{
site_name }}.{% endblocktranslate %}

{% translate "Please go to the following page and choose a new password:" %}
{% block reset_link %}
{{ protocol }}://{{ domain }}{% url 'courses:password_reset_confirm' uidb64=uid token=token %}
{% endblock %}
{% translate 'Your username, in case you’ve forgotten:' %} {{ user.get_username }}

{% translate "Thanks for using our site!" %}

{% blocktranslate %}The {{ site_name }} team{% endblocktranslate %}

{% endautoescape %}

courses/templates/courses/password_reset_email.html
{% load i18n %}{% autoescape off %}
{% blocktranslate %}You're receiving this email because you requested a password reset for your user account at {{
site_name }}.{% endblocktranslate %}

{% translate "Please go to the following page and choose a new password:" %}
{% block reset_link %}
{{ protocol }}://{{ domain }}{% url 'courses:password_reset_confirm' uidb64=uid token=token %}
{% endblock %}
{% translate 'Your username, in case you’ve forgotten:' %} {{ user.get_username }}

{% translate "Thanks for using our site!" %}

{% blocktranslate %}The {{ site_name }} team{% endblocktranslate %}

{% endautoescape %}

courses/templates/courses/password_reset_sent.html
{% extends 'courses/base.html' %}
{% block content %}

<div class="row justify-content-center py-3">
    <div class="login-wrap py-5">

        <h2 class="text-light text-center fw-bold fs-2">Password reset sent</h2>

        <p>We’ve emailed you instructions for setting your password, if an account exists with the email you entered.
            You should receive them shortly.</p>

        <p>If you don’t receive an email, please make sure you’ve entered the address you registered with, and check
            your spam folder.</p>

    </div>
</div>



{% endblock %}

courses/templates/courses/reset_password.html
{% extends 'courses/base.html' %}
{% block content %}

<h1>Forgot your password?</h1>
<p>Enter your email address below, and we'll email instructions for setting a new one.</p>

<form method="POST">
    {% csrf_token %}
    <input type="email" name="email" id="id_email" required placeholder="Email Address" autocomplete="email">
    <div>
        <p>{{msg}}</p>
    </div>
    {% if status == "success" %}
    <div>
        <button class="btn btn-primary"><a href="{% url 'courses:login' %}">Login</a></button>
    </div>
    {% endif %}

    <input type="submit" name="Send email" value="Send me instructions!">
</form>
{% endblock %}

courses/templates/courses/search.html
{% extends 'courses/base.html' %}

{% block content %}
<div class="slogan text-light">
    <div class="slogan-container">
        <h1>Result for <span class="fst-italic text-warning">{{keyword}}</span> </h1>
    </div>
</div>
<!-- Search bar -->
<div class=" my-2 mb-3 search-bar ">
    <form class="input-group" action="{% url 'courses:search_course' %}">
        <input class="form-control rounded-start" type="text" name="key" placeholder="Python, JavaScript, Swift...">
        <button class="btn-outline-light bg-info text-dark rounded-end" type="submit"><i
                class="fas fa-search px-2"></i></button>
    </form>
</div>
<div class="d-flex justify-content-center align-items-center ">
    {% if not courses %}
    <h4 class="my-3 text-white">No results found </h4>
    {% else %}

    <div class="container grid-view">
        {% include "courses/course_template.html" with courses=courses %}
    </div>
    {% endif %}

</div>
{% endblock content %}

courses/templates/courses/suggest_course.html
{% extends 'courses/base.html' %}
{% load static %}

{% block content %}

<main>
    <div class="slogan text-light bg-dark">
        <div class="slogan-container">
            <h1 class="mb-3">Share your course</h1>
            <p class="fs-6">Your submission will be carefully reviewed and only published once it has passed the
                verification </p>
        </div>
    </div>
    <div class="container">
        <div id="forms" class="pb-3 pt-3 pb-5">
            <!-- Form -->
            <form class="form mx-auto" method='POST' action="{% url 'courses:suggest_course' %}">{% csrf_token %}
                <div class="input-group row">
                    <label
                        class="col-lg-2 col-md-1 col-form-label form-control-label text-light justify-content-end align-items-center d-lg-flex ">Name</label>
                    <div class="col-md-5 col-lg-4">
                        <input class="form-control mb-2" id="id_name" type="text" name="name"
                            value="{{form.name.value}}" placeholder="James">
                    </div>
                    <label
                        class="col-lg-2 col-md-1 col-form-label form-control-label text-light justify-content-end align-items-center d-lg-flex">Email</label>
                    <div class="col-md-5 col-lg-4">
                        <input class="form-control mb-lg-2" id="id_email" type="text" name="email"
                            value="{{form.email.value}}" placeholder="email@gmail.com">
                    </div>
                </div>

                <div class="input-group row mt-2 mt-lg-4">
                    <label
                        class="col-lg-2 col-form-label form-control-label  justify-content-end align-items-center d-lg-flex text-light ">Course
                        Name</label>
                    <div class="col-lg">
                        <input class="form-control" id="id_course_name" type="text" name="course_name"
                            placeholder="Django from zero to hero" value="{{form.course_name.value}}" required>
                    </div>
                </div>
                <div class="input-group row mt-2 mt-lg-4">
                    <label
                        class="col-lg-2 col-form-label form-control-label text-light justify-content-end align-items-center d-lg-flex">Course
                        URL</label>
                    <div class="col-lg-10">
                        <input class="form-control" id="id_course_url" name="course_url" type="text" placeholder=""
                            value="{{form.course_url.value}}" required>
                    </div>
                </div>
                <div class="input-group row mt-2 mt-lg-4">
                    <label
                        class="col-lg-2 col-form-label form-control-label text-light justify-content-end align-items-center d-lg-flex">Description</label>
                    <div class="col-lg-10">
                        <input class="form-control" id="id_description" type="text" name="description" required
                            placeholder="This course will give you a full introduction into all of the core concepts in python."
                            value="{{form.description.value}}">
                    </div>
                </div>

                {% if form.errors %}
                <div class="input-group row">
                    <label class="col-lg-2 col-md-1"></label>
                    <div class="col pt-3">
                        {% if form.errors.name %}
                        <p class="text-danger py-0">Name is too long, it should be less than 150 characters</p>
                        {% elif form.errors.email %}
                        <p class="text-danger py-0">{{form.errors.get_json_data.email.0.message}}</p>
                        {% else %}
                        <p class="text-danger py-0">Please enter a valid Course URL</p>
                        {% endif %}
                    </div>
                </div>
                {% endif %}
                {% if success %}
                <div class="input-group row">
                    <label class="col-lg-2 col-md-1"></label>
                    <div class="col pt-3">
                        <p class="text-info py-0">Thank you for your sharing!</p>
                    </div>
                    {% endif %}
                    <div class="input-group row mt-2 mt-lg-3">
                        <label class="col-lg-2"></label>
                        <div class="col-lg-10">
                            <input type="reset" class="btn btn-outline-secondary mr-2" value="Cancel">
                            <input type="submit" class="btn btn-primary mr-2" name="submit" value="Submit">
                        </div>
                    </div>
            </form>

        </div>
    </div>





</main>


{% endblock %}